AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service

Parameters:
  ClusterName:
    Type: String
    Description: Name of the ECS Cluster (import from ECS Cluster stack)
  TaskDefinitionArn:
    Type: String
    Description: ARN of the ECS Task Definition (import from TaskDef stack)
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of public subnet IDs (import from VPC stack)
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for ECS tasks (import from SG or VPC stack)
  TargetGroupArn:
    Type: String
    Description: Target Group ARN for ALB (import from ALB stack)

Resources:
  AppService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref TaskDefinitionArn
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: [!Ref SecurityGroupId]
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroupArn
          ContainerName: app   # Must match the container name in your Task Definition
          ContainerPort: 80
      HealthCheckGracePeriodSeconds: 60

Outputs:
  ServiceName:
    Description: Name of the ECS Service
    Value: !Ref AppService
    Export:
      Name: !Sub "${AWS::StackName}-ServiceName"
  ServiceArn:
    Description: ARN of the ECS Service
    Value: !GetAtt AppService.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ServiceArn"
