AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition

Parameters:
  ECRImageUri:
    Type: String

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  AppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: app-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: app
          Image: !Ref ECRImageUri
          PortMappings:
            - ContainerPort: 80
          #HealthCheck:
           # Command: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
            #Interval: 30
            #Timeout: 5
            #Retries: 3
            #StartPeriod: 10
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/app
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: app

Outputs:
  TaskDefinitionArn:
    Value: !Ref AppTaskDefinition
    Export:
      Name: !Sub "${AWS::StackName}-TaskDefArn"
