Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"

  PublicSubnets:
    Description: Comma-delimited list of public subnet IDs
    Value: !Join [",", [!Ref PublicSubnet1, !Ref PublicSubnet2]]
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnets"

  SecurityGroupId:
    Description: Default security group ID
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId"
