Parameters:
  GitHubRepo:
    Type: String

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "cicd-ecr-build"
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
        BuildSpec: "buildspec.yml"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/standard:5.0"
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: "225989367454"
          - Name: AWS_REGION
            Value: "eu-west-2"
