AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for building and pushing Docker images to ECR

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository (e.g., naghi20/CICD_ECR)
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to build from
  ECRRepositoryUri:
    Type: String
    Description: ECR repository URI (e.g., 123456789012.dkr.ecr.eu-west-2.amazonaws.com/cicd-ecr-repo)

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ECRPushAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:CreateRepository
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cicd-ecr-build
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubRepo}.git"
        GitCloneDepth: 1
        BuildSpec: buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true # Needed for Docker builds
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref "AWS::Region"
          - Name: AWS_ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: AWS_REGION
            Value: !Ref "AWS::Region"
          - Name: ECR_REPO_URI
            Value: !Ref ECRRepositoryUri
      Artifacts:
        Type: NO_ARTIFACTS
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: 30

Outputs:
  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildProjectName"
  CodeBuildRoleArn:
    Description: ARN of the CodeBuild IAM Role
    Value: !GetAtt CodeBuildRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildRoleArn"
